### ISSUE TITLE
Stuck at waiting resources to compile

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [Rutuj-Runwal/Xylent#13]
![image](https://github.com/Rutuj-Runwal/Xylent/assets/142328963/9fcba9f4-21b0-487e-bae2-0e51aa534451)
I deleted biggest yara rules but it still stuck at waiting resources to compile. Also compiled rules not being to created.

**Comment by Rutuj-Runwal** [comment]
If the rules have any compilation error, it will not be able to compile them.
To check the error:
go into `scanner.py`
Add a break statement after line no 24 `print("Waiting for resources to compile...")`
Rerun `engine.py`

Alternatively you can add debug print statements to identify which yara rule is causing the issue.
I will be adding a global logging system soon as per #10 
The error is yara rules related so you will have to check for errors in your yara rules.

**Comment by HydraDragonAntivirus** [comment]
Look my pull request. Sorry I should add there but idk how can I do that.

**Comment by HydraDragonAntivirus** [comment]
Are you here the pull request didn't accepted yet so I'm going to reopen that.
